minVersion: 2.18.0
github:
  owner: getsentry
  repo: rust-usage-accountant
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: none

preReleaseCommand: bash ./scripts/bump-version.sh
targets:
  - name: crates
  - name: github
